# Generated by Django 3.2.23 on 2023-11-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='confirmation_code',
            field=models.CharField(default=62872, max_length=5),
        ),
    ]
