# Generated by Django 3.2.23 on 2023-11-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='confirmation_code',
            field=models.CharField(default=38339, max_length=5),
        ),
    ]
