# Generated by Django 3.2.23 on 2023-11-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_confirmation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='users',
            name='confirmation_code',
            field=models.CharField(default=38457, max_length=5),
        ),
    ]
