# Generated by Django 3.2.23 on 2023-11-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20231108_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='confirmation_code',
            field=models.CharField(default=10949, max_length=5),
        ),
    ]
