# Generated by Django 3.2.23 on 2023-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20231112_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='referral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='confirmation_code',
            field=models.CharField(default=74372, max_length=5),
        ),
    ]
