# Generated by Django 3.2.23 on 2023-11-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='click_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='cpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='cpc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
